import type { Metadata } from 'next';
import { Raleway, Geologica } from 'next/font/google';

import { Header, Footer } from '@/layout';

import './globals.css';

const raleway = Raleway({
  subsets: ['cyrillic', 'latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-raleway',
  display: 'swap',
});

const geologica = Geologica({
  subsets: ['cyrillic'],
  weight: ['200', '300', '400', '500', '700'],
  variable: '--font-geologica',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Spilno',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body className={`${raleway.variable} ${geologica.variable}`}>
        <Header />
        <main>{children}</main>
        <Footer />
        <div id="modal-portal" />
      </body>
    </html>
  );
}
